name: Self-Healing Selenium Test
 
on:
  push:
    paths:
      - 'tests/**'
      - 'agents/**'
      - '.github/workflows/**'
 
jobs:
  test-and-heal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
 
      - name: Install dependencies
        run: pip install -r requirements.txt
 
      - name: Run test + healing
        run: python main.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
